operatorfabric:
  security:
    oauth2:
      flow:
        mode: CODE
        provider: Opfab Keycloak
        delagate-url: http://localhost:89/auth/realms/dev/protocol/openid-connect/auth?response_type=code&client_id=opfab-client
  feed:
    subscription:
      timeout: 600000
    card:
      time:
        display: BUSINESS
  i10n.supported.time-zones:
  - Europe/Paris
  - Europe/London
  - Europe/Dublin
  - Europe/Brussel
  - Europe/Berlin
  - Europe/Rome
  - Europe/Madrid
  - Europe/Lisbon
  - Europe/Amsterdam
  - Europe/Athens
  - Australia/Melbourne
  - Pacific/Samoa
  i18n.supported.locales:
  - fr
  - en
