version: '2.1'
services:
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
      - "15674:15674"
  mongodb:
    container_name: mongodb
    image: mongo:4.1.1-xenial
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
  keycloak:
    container_name: keycloak
    image: jboss/keycloak
    command: -Dkeycloak.migration.actions=import -Dkeycloak.migration.provider=dir -Dkeycloak.migration.dir=/realms/export
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
      - DB_VENDOR=H2
    volumes:
      - ../realms:/realms
    ports:
      - "89:8080"
      - "90:9990"

